jwt:
  token:
    secret-key:
      access: YWNjZXNzLXRva2VuYWNjZXNzLXRva2VuYWNjZXNzLXRva2Vu
      refresh: cmVmcmVzaC10b2tlbnJlZnJlc2gtdG9rZW5yZWZyZXNoLXRva2Vu
    expired-time-ms:
      access: 25920000
      refresh: 2592000000