name: PR Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          ./gradlew build
